### ISSUE TITLE
Your local Keycloak doesn't seem to be running.

### ISSUE THREAD

**Issue by CertainPassenger** [keycloakify/keycloakify-starter#27]
Hello,

sorry I this is not the correct Github project for this issue.  I'm trying to follow the tutorial to check out Keycloakify. The steps I've follow were:
1. Cloning the Keycloakify starter `git clone https://github.com/keycloakify/keycloakify-starter` as mentioned here: https://docs.keycloakify.dev/
2. Changing directory `cd keycloakify-starter`
3. `yarn install`
4. Testing the theme locally using Docker `npx keycloakify start-keycloak` (I've used version 25.0)

After that everything appears to be running 

```
The ftl files from ./dist_keycloak/theme are mounted in the Keycloak container.

Keycloak Admin console: http://localhost:8080
- user:     admin
- password: admin


Your theme is accessible at:
➜ https://my-theme.keycloakify.dev/

You can login with the following credentials:
- username: testuser
- password: password123

Watching for changes in ./
```

However, when I follow the link to https://my-theme.keycloakify.dev/ as mentioned in the tutorial, I get the error `Your local Keycloak doesn't seem to be running. Please refer to the [documentation](https://docs.keycloakify.dev/testing-your-theme/in-a-keycloak-docker-container).`

However, the output of `docker ps` shows that the Docker container is running and ports are forwarded

```
CONTAINER ID   IMAGE                            COMMAND                  CREATED              STATUS              PORTS                                                           NAMES
b7c0bd51e41a   quay.io/keycloak/keycloak:25.0   "/opt/keycloak/bin/k…"   About a minute ago   Up About a minute   8443/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 9000/tcp   keycloak-keycloakify
```

Are there any steps that I'm missing?

**Comment by garronej** [comment]
Hello @CertainPassenger,  

Sorry to heare you are experiencing an issue.  

There might be some securities policies in place on the browser you are using that prevent opening an iframe to a non https location. It's the case for Safari.  So I display [this message](https://github.com/keycloakify/keycloakify/issues/576#issuecomment-2205655812).  

What web browser are you using by default, on which OS?  

Mabe try with chrome and let me know if it work.  

Also try to see if you can access `http://localhost:8080`

**Comment by CertainPassenger** [comment]
@garronej 

Thanks! Your comment helped me narrowing down the issue! I am using Microsoft Edge on Linux (Ubuntu 24.04), however the issue was the addon uBlock Origin. After disabling the addon the redirect worked without any problems.

**Comment by garronej** [comment]
Thank for reporting back, I've added a notice on the my-theme app: https://github.com/keycloakify/my-theme.keycloakify.dev/commit/b2ed572bf54e3b4891fcfce62250ba97bec7c3c4
