### ISSUE TITLE
Building the .jar file fails

### ISSUE THREAD

**Issue by abdeljalil-salhi** [keycloakify/keycloakify-starter#30]
I want to use the keycloakify in my project, but it keeps failing when trying to build the theme.

So, just to make sure, I cloned a new repo of keycloakify-starter and directly tried to build it, and it still failed for me;

<img width="1164" alt="Screenshot 2024-09-15 at 20 20 02" src="https://github.com/user-attachments/assets/366ca3e7-ed3b-4756-b075-948dcccde386">

and when i tried to run the failed command separately, this is what i got:

<img width="1168" alt="Screenshot 2024-09-15 at 20 22 45" src="https://github.com/user-attachments/assets/1056b573-f83d-4db7-9fdb-c981893d1122">

I don't know if I should do something from my end when it says there is no POM file in this directory, because looking at other keycloakify tutorials it works just great after cloning the repo as it is...

**Comment by garronej** [comment]
Hello @abdeljalil-salhi,  

Can you share with me your package.json and vite.config.ts file?

**Comment by abdeljalil-salhi** [comment]
Hello @garronej,

As I said, I took a new clone of keyclokify-starter without changing anything and tried to build it, and it still failed;

<img width="1464" alt="Screenshot 2024-09-15 at 21 44 56" src="https://github.com/user-attachments/assets/691f51a1-ceae-46e8-bf3f-eb989ae73de1">

**Comment by garronej** [comment]
What do you get when you run:  

```bash
mvn --version
yarn --version
```

?

**Comment by abdeljalil-salhi** [comment]
@garronej 
I use npm not yarn

and i downloaded mvn using `brew install mvn` as requested in the docs;

<img width="1406" alt="Screenshot 2024-09-15 at 22 09 39" src="https://github.com/user-attachments/assets/7a9b9dbe-c6c5-43b8-9edc-02e1c0e2c382">

**Comment by garronej** [comment]
Please try this and tell me if it work:  

```bash
git clone https://github.com/keycloakify/keycloakify-starter
cd keycloakify-starter
yarn
yarn build-keycloak-theme
```

Tell me if it work. If you don't have yarn you can install it with `npm install -g yarn`.  

Also show me the result of `node -v`

**Comment by abdeljalil-salhi** [comment]
@garronej 

I tried with yarn, and still the same error, below are the versions of yarn and node

<img width="1405" alt="Screenshot 2024-09-15 at 22 39 25" src="https://github.com/user-attachments/assets/5d178c13-b1af-47f7-b8ae-5bca1f2ee0c7">

**Comment by tripheo0412** [comment]
Hi, I got the same error. Using the starter theme
![image](https://github.com/user-attachments/assets/a4150c81-1414-4622-8ee0-23910fef16dc)

**Comment by garronej** [comment]
@abdeljalil-salhi 

I'm perplex.  

Can you try with `terminal.app`:  

```bash
cd ~
mkdir github
git clone https://github.com/keycloakify/keycloakify-starter
cd keycloakify-starter
yarn
yarn build-keycloak-theme
```

Run theses exact commands and tell me what you're getting.  

@tripheo0412 Can you open another issue, it's likely not the same issue as @abdeljalil-salhi, in the issue you open please include your package.json and your vite.config.ts.

**Comment by tripheo0412** [comment]
@garronej I think it is very similar, seems like it is trying to find pom.xml in the root directory even though the file exist in `apps/keycloak-theme/node_modules/.cache/keycloakify/maven/vahterus-keycloak-theme/pom.xml`

![image](https://github.com/user-attachments/assets/40c33afc-c11c-401c-97f7-4e511d643901)

**Comment by abdeljalil-salhi** [comment]
@garronej 

Following the exact same commands in Terminal, still the same issue:

<img width="995" alt="Screenshot 2024-09-15 at 23 06 22" src="https://github.com/user-attachments/assets/e4e45182-9fd0-4838-a140-af577265d406">
<img width="983" alt="Screenshot 2024-09-15 at 23 06 45" src="https://github.com/user-attachments/assets/d9a4d8fe-5f14-4f9d-b261-121b49df2fc7">

And yes, I can tell I have the same issue as @tripheo0412

**Comment by tripheo0412** [comment]
If I go directly to keycloakify/maven/my-theme (or keycloak-theme-for-kc-22-and-above) and run `maven build`

![image](https://github.com/user-attachments/assets/42302863-6f50-4b99-a9b8-b64a93cca9b4)

**Comment by garronej** [comment]
@tripheo0412 Please open another issue. And share your `vite.config.ts` and your `package.json`.  

@abdeljalil-salhi It's not the same issue, trust me.  
What shell are you using?

**Comment by garronej** [comment]
Fixed. It was a proxy issue. When using an HTTP proxy Maven need to be configured to use it.
