### ISSUE TITLE
Building theme failed

### ISSUE THREAD

**Issue by tripheo0412** [keycloakify/keycloakify-starter#31]
I got an error when run `npm run build-keycloak-theme`. I custom the login page with tailwind and shadcn.

Environment:
Node 22.1.0
Maven 3.9.9
NPM 10.7.0
Mac OS Sonoma 14.5

**vite.config.ts**

![image](https://github.com/user-attachments/assets/a3a66939-ccd7-4259-9fad-93054795cd3a)

**package.json**

![image](https://github.com/user-attachments/assets/bf893e09-2e98-4b8e-8a3e-5a195febe7af)

**Comment by garronej** [comment]
Hi @tripheo0412,  

At the moment you can't have spaces in the theme name.  
Use `vantheus-authentication`

**Comment by tripheo0412** [comment]
@garronej works like a charm, thank you very much, this is an awesome project!
