### ISSUE TITLE
Error with Vite: An import map is added after module script load was triggered.

### ISSUE THREAD

**Issue by tripheo0412** [keycloakify/keycloakify-starter#32]
Step to reproduce:

1.  `git clone https://github.com/keycloakify/keycloakify-starter`
2.  `yarn install`
3.  Un comment this block in main.tsx
```
import { getKcContextMock } from "./login/KcPageStory";

if (import.meta.env.DEV) {
  window.kcContext = getKcContextMock({
    pageId: "login.ftl",
    overrides: {}
  });
}
```
4. `yarn dev`
5.  Open browser and check browser console. Got `Error with Vite: An import map is added after module script load was triggered.` 

![image](https://github.com/user-attachments/assets/082b6c2a-5241-4967-b22c-b73b38c9c114)

Everything is stock, from the starter. If I keep the mock commented and build-keycloak-theme, then upload the jar to keycloak 25, this error still happens.

**Comment by garronej** [comment]
Hello @tripheo0412,  

I fixed this earlyer today, just update to the latest Keycloakify verison :)

**Comment by tripheo0412** [comment]
solve by updating to keycloakify 10.1.4
