### ISSUE TITLE
Error on maven install

### ISSUE THREAD

**Issue by deincodeverbesserer93** [keycloakify/keycloakify-starter#33]
Hello,

when i try to run the build command. I get the error **Error: Command failed: mvn install -...**.
I tried the keycloakify v10 starter project .. and only added the account theme like your documentation.
When i try my keycloakify v9 project no error occurs.

`npm run build-keycloak-theme                                                                                                                        

> keycloakify-starter@0.0.0 build-keycloak-theme
> npm run build && keycloakify build

> keycloakify-starter@0.0.0 build
> tsc && vite build

vite v5.2.13 building for production...
✓ 3797 modules transformed.
dist/index.html                                                 0.39 kB │ gzip:   0.26 kB
dist/assets/pf-v5-pficon-Di6gTOT4.woff2                        18.46 kB
....
✓ built in 6.68s
keycloakify v10.1.4 Building the keycloak theme in ./dist_keycloak ...
Build jar failed: {
  "jarFileBasename": "my-keycloak-theme.jar",
  "keycloakAccountV1Version": null,
  "keycloakThemeAdditionalInfoExtensionVersion": "1.1.5"
}

**Error: Command failed: mvn install -Dmaven.repo.local="/Users/Shared/dev/KeyCloak/source/keycloakify_10.0.0_1/node_modules/.cache/keycloakify/maven/my-keycloak-theme/.m2"**

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'mvn install -Dmaven.repo.local="/Users/Shared/dev/KeyCloak/source/keycloakify_10.0.0_1/node_modules/.cache/keycloakify/maven/my-keycloak-theme/.m2"'
}
`

**Comment by garronej** [comment]
Hello @deincodeverbesserer93,  

You are probably behind some company proxy. You need to configure maven so it can download the required dependencies.

**Comment by deincodeverbesserer93** [comment]
Hello @garronej,

i checked this as first. But tried this at home without vpn and with vpn. I also tried this in my office.
How can i configure maven? I also have deleted my proxy configuration in maven but nothing helped

**Comment by deincodeverbesserer93** [comment]
Hello,

when i run only **mvn install** in  /node_modules/.bin/.cache/keycloakify/maven/my-keycloak-theme
and i modify **pom.xml** in /node_modules/.bin/.cache/keycloakify/maven/my-keycloak-theme

and delete the section with

```
 <dependency>
      <groupId>dev.jcputney</groupId>
      <artifactId>keycloak-theme-additional-info-extension</artifactId>
      <version>1.1.5</version>
    </dependency>
```

than the jar file will generated. But this is no solution.
Do you have any known problems?

i testet this with the keycloakify 11 starter tag branch

**Comment by garronej** [comment]
I should really make the error more apparent.  
There isn't any known issue besides the users behind a VPN or a HTTP Proxy.  
I am almost positive that your instance of Maven do not have access to the internet on your machine.  
Try building your code on codespace you'll see that it work.

**Comment by deincodeverbesserer93** [comment]
i found the solution.
the real error when i use mvn install in the path for myself was ** PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path**
 
i added download the certificate.pem-file from https://repo.maven.apache.org/maven2 and included to the java home directory. I used the application Keystore Explorer and used the below path and file

``
/Users/YOUR_USERNAME/Library/Java/JavaVirtualMachines/openjdk-20.0.2/Contents/Home/lib/security 
``
in the **cacerts** file

**Comment by garronej** [comment]
Thanks for reporting your solution.  
It was indeed that maven wasn't able to download the extention.  
Don't know why you needed to go through all thoses shanenigan to make it work though...
